import { createFileRoute } from "@tanstack/react-router";
import { LegalShell } from "@/components/site/LegalShell";
import { useI18n } from "@/lib/i18n";
import { BUSINESS } from "@/content/business";

export const Route = createFileRoute("/privacy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy | SPA NAZ" },
      {
        name: "description",
        content: "How SPA NAZ processes booking and account data under the GDPR.",
      },
    ],
    links: [{ rel: "canonical", href: "https://spanaz.ro/privacy" }],
  }),
  component: PrivacyPage,
});

function PrivacyPage() {
  const { lang } = useI18n();
  const ro = lang === "ro";

  return (
    <LegalShell
      eyebrow={ro ? "CONFIDENȚIALITATE" : "PRIVACY"}
      title={ro ? "Politica de confidențialitate" : "Privacy Policy"}
      intro={
        ro
          ? "Această informare descrie transparent datele pe care SPA NAZ le prelucrează, de ce sunt necesare și ce drepturi ai conform Regulamentului (UE) 2016/679 (GDPR)."
          : "This notice explains the personal data SPA NAZ processes, why it is needed and the rights available to you under Regulation (EU) 2016/679 (GDPR)."
      }
      updated={ro ? "Versiune: 19 septembrie 2026" : "Version: 19 September 2026"}
    >
      <section>
        <h2>{ro ? "1. Operatorul de date" : "1. Data controller"}</h2>
        <p>
          {ro
            ? `Operatorul este SPA NAZ, București, România. Pentru întrebări sau cereri privind datele personale: ${BUSINESS.email}.`
            : `The controller is SPA NAZ, Bucharest, Romania. For privacy questions or data requests: ${BUSINESS.email}.`}
        </p>
      </section>

      <section>
        <h2>{ro ? "2. Ce date colectăm" : "2. Data we collect"}</h2>
        <ul>
          <li>
            {ro
              ? "pentru rezervare: nume, un singur număr de telefon/WhatsApp, serviciul și durata selectate, data și ora solicitate, sectorul, adresa, numărul de persoane și mesajul opțional;"
              : "for booking: name, one phone/WhatsApp number, selected service and duration, requested date and time, sector, address, number of people and optional message;"}
          </li>
          <li>
            {ro
              ? "pentru cont: adresa de email, identificatorul Firebase, starea verificării emailului și identificatorii tehnici necesari autentificării;"
              : "for your account: email address, Firebase user identifier, email-verification status and technical authentication identifiers;"}
          </li>
          <li>
            {ro
              ? "pentru securitate și funcționare: date tehnice limitate generate de Firebase și Cloudflare pentru autentificare, livrare și protecția serviciului."
              : "for security and operation: limited technical data generated by Firebase and Cloudflare for authentication, delivery and service protection."}
          </li>
        </ul>
        <p>
          {ro
            ? "SPA NAZ aplică principiul minimizării datelor: formularul nu solicită informații medicale și nu trebuie folosit pentru a trimite diagnostice, documente medicale sau alte categorii speciale de date."
            : "SPA NAZ applies data minimisation: the booking form does not ask for medical information and should not be used to send diagnoses, medical documents or other special-category data."}
        </p>
      </section>

      <section>
        <h2>{ro ? "3. Scopuri și temeiuri juridice" : "3. Purposes and legal bases"}</h2>
        <ul>
          <li>
            {ro
              ? "Gestionarea rezervării, contactarea clientului, confirmarea sau modificarea programării: art. 6 alin. (1) lit. (b) GDPR — demersuri la cererea persoanei înainte de prestarea serviciului și executarea serviciului."
              : "Managing the booking, contacting the customer and confirming or changing the appointment: GDPR Article 6(1)(b) — steps taken at your request before providing the service and performance of the service."}
          </li>
          <li>
            {ro
              ? "Crearea și funcționarea contului solicitat de utilizator: art. 6 alin. (1) lit. (b) GDPR."
              : "Creating and operating the account requested by the user: GDPR Article 6(1)(b)."}
          </li>
          <li>
            {ro
              ? "Securitatea site-ului, prevenirea abuzului și protejarea sistemului de rezervări: art. 6 alin. (1) lit. (f) GDPR — interes legitim, cu respectarea drepturilor utilizatorului."
              : "Site security, abuse prevention and protection of the booking system: GDPR Article 6(1)(f) — legitimate interests, balanced against user rights."}
          </li>
          <li>
            {ro
              ? "Îndeplinirea obligațiilor legale aplicabile, atunci când este necesar: art. 6 alin. (1) lit. (c) GDPR."
              : "Compliance with applicable legal obligations where required: GDPR Article 6(1)(c)."}
          </li>
        </ul>
        <p>
          {ro
            ? "Nu bazăm procesarea necesară rezervării pe consimțământ. Formularul îți cere să confirmi că ai citit această informare și că accepți termenii serviciului. Orice viitoare comunicare de marketing ar necesita o opțiune separată și voluntară."
            : "Processing necessary for a booking is not based on consent. The form records that you received this privacy notice and accepted the service terms. Any future marketing communication would require a separate, voluntary opt-in."}
        </p>
      </section>

      <section>
        <h2>{ro ? "4. Destinatari și furnizori" : "4. Recipients and providers"}</h2>
        <p>
          {ro
            ? "Datele sunt accesibile numai în măsura necesară funcționării serviciului. SPA NAZ folosește Google Firebase pentru autentificare și stocarea rezervărilor și Cloudflare pentru găzduire, livrare și securitate. Datele de rezervare sunt accesibile proprietarului autorizat SPA NAZ prin panoul administrativ."
            : "Data is accessible only as needed to operate the service. SPA NAZ uses Google Firebase for authentication and booking storage and Cloudflare for hosting, delivery and security. Booking data is accessible to the authorized SPA NAZ owner through the admin dashboard."}
        </p>
        <p>
          {ro
            ? "Acești furnizori operează infrastructură internațională și pot utiliza mecanisme legale aplicabile pentru transferurile de date în afara Spațiului Economic European."
            : "These providers operate international infrastructure and may rely on applicable legal safeguards for transfers outside the European Economic Area."}
        </p>
      </section>

      <section>
        <h2>{ro ? "5. Păstrarea datelor" : "5. Retention"}</h2>
        <p>
          {ro
            ? "În mod normal, evidențele operaționale ale rezervărilor sunt păstrate până la 24 de luni după finalizare sau anulare. O perioadă mai lungă poate fi necesară pentru obligații legale, contabilitate sau soluționarea unui litigiu. Datele contului sunt păstrate cât timp contul rămâne activ sau până când este solicitată ștergerea, sub rezerva obligațiilor legale aplicabile."
            : "Operational booking records are normally retained for up to 24 months after completion or cancellation. A longer period may be required for legal obligations, accounting or dispute handling. Account data is retained while the account remains active or until deletion is requested, subject to applicable legal obligations."}
        </p>
      </section>

      <section>
        <h2>{ro ? "6. Drepturile tale" : "6. Your rights"}</h2>
        <p>
          {ro
            ? "În condițiile GDPR, poți solicita accesul la date, rectificarea, ștergerea, restricționarea prelucrării, portabilitatea și opoziția atunci când aceste drepturi sunt aplicabile. Poți solicita aceste acțiuni din pagina contului sau prin email."
            : "Where applicable under the GDPR, you may request access, correction, erasure, restriction, portability and objection. You can initiate a request from the account page or by email."}
        </p>
        <p>
          {ro
            ? "Ai dreptul să depui o plângere la Autoritatea Națională de Supraveghere a Prelucrării Datelor cu Caracter Personal (ANSPDCP), Bd. G-ral Gheorghe Magheru 28-30, Sector 1, București, email anspdcp@dataprotection.ro."
            : "You may lodge a complaint with Romania's National Supervisory Authority for Personal Data Processing (ANSPDCP), 28-30 G-ral Gheorghe Magheru Blvd., District 1, Bucharest, email anspdcp@dataprotection.ro."}
        </p>
      </section>

      <section>
        <h2>{ro ? "7. Decizii automate și marketing" : "7. Automated decisions and marketing"}</h2>
        <p>
          {ro
            ? "SPA NAZ nu folosește datele de rezervare pentru decizii exclusiv automatizate care produc efecte juridice asupra clientului și nu folosește datele de rezervare pentru marketing fără o bază legală și o opțiune separată."
            : "SPA NAZ does not use booking data for solely automated decisions that produce legal effects for the customer and does not use booking data for marketing without an appropriate legal basis and a separate opt-in."}
        </p>
      </section>

      <section>
        <h2>{ro ? "8. Stocare în browser și cookie-uri" : "8. Browser storage and cookies"}</h2>
        <p>
          {ro
            ? "Site-ul folosește stocare locală necesară pentru autentificare, preferința de limbă și funcționarea contului. În versiunea actuală nu folosim cookie-uri publicitare sau de analiză comportamentală. Dacă vor fi introduse tehnologii neesențiale, acestea vor fi gestionate separat înainte de activare."
            : "The site uses necessary local browser storage for authentication, language preference and account operation. The current version does not use advertising or behavioural-analytics cookies. If non-essential technologies are introduced, they will be handled separately before activation."}
        </p>
      </section>

      <section>
        <h2>{ro ? "9. Securitate și contact" : "9. Security and contact"}</h2>
        <p>
          {ro
            ? "SPA NAZ aplică restricții de acces, reguli Firestore și autentificare pentru a limita accesul la date. Nicio metodă online nu poate garanta securitate absolută, dar accesul la rezervări este limitat la clientul asociat și proprietarul autorizat."
            : "SPA NAZ uses access controls, Firestore rules and authentication to restrict access to data. No online method can guarantee absolute security, but booking access is limited to the linked customer and the authorized owner."}
        </p>
        <p>
          {ro
            ? `Pentru orice cerere legată de date personale, scrie la ${BUSINESS.email} de la adresa asociată contului sau menționează referința rezervării relevante.`
            : `For a personal-data request, email ${BUSINESS.email} from the address associated with your account or provide the relevant booking reference.`}
        </p>
      </section>
    </LegalShell>
  );
}
