import { createFileRoute } from "@tanstack/react-router";
import { LegalShell } from "@/components/site/LegalShell";
import { useI18n } from "@/lib/i18n";
import { BUSINESS } from "@/content/business";

export const Route = createFileRoute("/privacy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy | SPA NAZ" },
      {
        name: "description",
        content: "How SPA NAZ collects and uses booking and account data.",
      },
    ],
    links: [{ rel: "canonical", href: "https://spanaz.ro/privacy" }],
  }),
  component: PrivacyPage,
});

function PrivacyPage() {
  const { lang } = useI18n();
  const ro = lang === "ro";

  return (
    <LegalShell
      eyebrow={ro ? "CONFIDENȚIALITATE" : "PRIVACY"}
      title={ro ? "Politica de confidențialitate" : "Privacy Policy"}
      intro={
        ro
          ? "Această politică explică ce date folosește SPA NAZ atunci când creezi un cont, trimiți o cerere de programare sau contactezi serviciul."
          : "This policy explains what data SPA NAZ uses when you create an account, submit an appointment request or contact the service."
      }
      updated={ro ? "Ultima actualizare: 19 septembrie 2026" : "Last updated: 19 September 2026"}
    >
      <section>
        <h2>{ro ? "1. Operatorul de date" : "1. Data controller"}</h2>
        <p>
          {ro
            ? `Operatorul este SPA NAZ, București, România. Pentru întrebări privind datele personale ne poți contacta la ${BUSINESS.email}.`
            : `The controller is SPA NAZ, Bucharest, Romania. For privacy questions, contact ${BUSINESS.email}.`}
        </p>
      </section>

      <section>
        <h2>{ro ? "2. Datele pe care le colectăm" : "2. Data we collect"}</h2>
        <ul>
          <li>{ro ? "date de cont: adresa de email, identificatorul Firebase și starea verificării emailului;" : "account data: email address, Firebase user identifier and email-verification status;"}</li>
          <li>{ro ? "date de rezervare: nume, telefon, WhatsApp, serviciu, durată, dată, oră, sector, adresă, număr de persoane și mesajul opțional;" : "booking data: name, phone, WhatsApp, service, duration, date, time, sector, address, number of people and optional message;"}</li>
          <li>{ro ? "date operaționale și de securitate generate de furnizorii tehnici necesare funcționării și protejării serviciului." : "operational and security data generated by technical providers as needed to operate and protect the service."}</li>
        </ul>
      </section>

      <section>
        <h2>{ro ? "3. De ce folosim datele" : "3. Why we use the data"}</h2>
        <p>
          {ro
            ? "Folosim datele pentru a procesa cererile de programare, a comunica despre programări, a furniza funcțiile contului și a proteja serviciul împotriva abuzului."
            : "We use the data to process appointment requests, communicate about appointments, provide account features and protect the service against abuse."}
        </p>
        <p>
          {ro
            ? "Pentru rezervări și funcțiile solicitate ale contului, prelucrarea este necesară pentru pași realizați la cererea ta înaintea furnizării serviciului și pentru executarea serviciului. Pentru securitate și prevenirea abuzului putem avea un interes legitim în protejarea site-ului și a clienților."
            : "For bookings and requested account features, processing is necessary to take steps at your request before providing the service and to perform the service. For security and abuse prevention, we may rely on legitimate interests in protecting the site and customers."}
        </p>
      </section>

      <section>
        <h2>{ro ? "4. Furnizori tehnici" : "4. Technical providers"}</h2>
        <p>
          {ro
            ? "SPA NAZ folosește Google Firebase pentru autentificare și stocarea rezervărilor și Cloudflare pentru găzduire, livrare și securitate. Acești furnizori pot prelucra date în cadrul propriei infrastructuri și conform mecanismelor lor de protecție a datelor."
            : "SPA NAZ uses Google Firebase for authentication and booking storage and Cloudflare for hosting, delivery and security. These providers may process data within their infrastructure and under their applicable data-protection safeguards."}
        </p>
      </section>

      <section>
        <h2>{ro ? "5. Perioada de păstrare" : "5. Retention"}</h2>
        <p>
          {ro
            ? "În mod normal, evidențele operaționale ale rezervărilor sunt păstrate până la 24 de luni după finalizarea sau anularea programării, cu excepția situațiilor în care o perioadă mai lungă este necesară pentru obligații legale sau soluționarea unui litigiu. Datele contului sunt păstrate cât timp contul rămâne activ sau până când este solicitată ștergerea, sub rezerva obligațiilor legale aplicabile."
            : "Operational booking records are normally retained for up to 24 months after completion or cancellation, unless a longer period is needed for legal obligations or dispute handling. Account data is retained while the account remains active or until deletion is requested, subject to applicable legal obligations."}
        </p>
      </section>

      <section>
        <h2>{ro ? "6. Drepturile tale" : "6. Your rights"}</h2>
        <p>
          {ro
            ? "În condițiile GDPR, poți solicita accesul, rectificarea, ștergerea, restricționarea prelucrării, opoziția și portabilitatea datelor, acolo unde acestea se aplică. Poți depune și o plângere la Autoritatea Națională de Supraveghere a Prelucrării Datelor cu Caracter Personal (ANSPDCP)."
            : "Under the GDPR, you may request access, correction, erasure, restriction, objection and data portability where applicable. You may also lodge a complaint with Romania's National Supervisory Authority for Personal Data Processing (ANSPDCP)."}
        </p>
      </section>

      <section>
        <h2>{ro ? "7. Contact" : "7. Contact"}</h2>
        <p>
          {ro
            ? `Pentru o cerere legată de date, scrie la ${BUSINESS.email}. Include suficiente informații pentru a putea identifica în siguranță contul sau rezervarea relevantă.`
            : `For a privacy request, email ${BUSINESS.email}. Include enough information for us to safely identify the relevant account or booking.`}
        </p>
      </section>
    </LegalShell>
  );
}
